version: '2'

services:
  indra:
    image: lambdacube/indra:latest
    container_name: indraserver
    ports:
      - "0.0.0.0:8916:8916"
    volumes:
      - ./data:/data
    environment:
      - INDRA_JAVA_OPTS=-Xmx20g -Dindra.http.host=0.0.0.0 -Dindra.http.port=8916 -Dindra.annoyBaseDir=/data/annoy -Dindra.luceneVectorsBaseDir=/data/lucene -Dindra.luceneTranslationBaseDir=/data/translation
