version: '2'

services:
  mongo:
    image: mongo:3.4
    container_name: indramongo
    command: --noprealloc --noauth --nojournal
    expose:
     - 27017
    volumes:
     - ./data/mongo/3.4/db:/data/db
     - ./dumps:/dumps
  

