version: '2'

services:
  mongo:
    image: mongo:3.0
    command: --noprealloc --noauth --nojournal
    expose:
     - 27017
    volumes:
     - "./data/mongo/3.0/db:/data/db"
  
  indra:
    image: lambdacube/indra:latest
    ports:
      - "0.0.0.0:8916:8916"
    environment:
      - INDRA_JAVA_OPTS=-Xmx4g -Dindra.http.host=0.0.0.0 -Dindra.mongoURI=mongo:27017
    links:
      - mongo
